openapi: 3.0.3
info:
  version: 'latest'
  title: CashQuest

servers:
  - url: 'http://localhost:8080'
security:
  - BearerAuth: [ ]

paths:
  '/ping':
    get:
      security: [ ]
      tags:
        - Security
      summary: ping-pong
      operationId: ping
      responses:
        200:
          description: pong
          content:
            application/json:
              schema:
                type: string
                example: pong
        500:
          $ref: '#/components/responses/500'
  '/whoami':
    get:
      security: [ BearerAuth: [ ] ]
      operationId: whoami
      responses:
        200:
          description: tells you who you are
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Whoami'
        400:
          $ref: "#/components/responses/400"
        403:
          $ref: '#/components/responses/500'
        429:
          $ref: "#/components/responses/400"
        500:
          $ref: '#/components/responses/500'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  responses:
    400:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BadRequestException'
    403:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NotAuthorizedException'
    404:
      description: Not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResourceNotFoundException'
    429:
      description: Too many requests to the API
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TooManyRequestsException'
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InternalServerException'
  schemas:
    User:
      type: object
      allOf:
        - $ref: "#/components/schemas/CreateUser"
    CreateUser:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
          format: email
        password:
          type: string
        birthDate:
          type: string
    Whoami:
      properties:
        user:
          $ref: '#/components/schemas/User'
    Page:
      type: integer
      description: Start at `1`
    PageSize:
      type: integer
      description: Cannot exceed `500`
    Exception:
      type: object
      properties:
        type:
          type: string
        message:
          type: string
    InternalServerException:
      allOf:
        - $ref: '#/components/schemas/Exception'
      example:
        type: InternalServerException
        message: Unexpected error
    BadRequestException:
      allOf:
        - $ref: '#/components/schemas/Exception'
      example:
        type: BadRequestException
        message: Bad request
    NotAuthorizedException:
      allOf:
        - $ref: '#/components/schemas/Exception'
      example:
        type: NotAuthorizedException
        message: Not authorized
    ResourceNotFoundException:
      allOf:
        - $ref: '#/components/schemas/Exception'
      example:
        type: ResourceNotFoundException
        message: Resource of type <T> identified by <I> not found
    TooManyRequestsException:
      allOf:
        - $ref: '#/components/schemas/Exception'
      example:
        type: TooManyRequestsException
        message: Too many requests